name: melon_mod
description: "Minecraft Fabric/Quilt mod manager for Windows desktop."
publish_to: 'none'
version: 1.0.0-beta.3+1
homepage: https://github.com/xyrusL/melon_mod_manager
repository: https://github.com/xyrusL/melon_mod_manager
issue_tracker: https://github.com/xyrusL/melon_mod_manager/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  archive: ^3.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  collection: ^1.18.0
  google_fonts: ^6.2.1
  crypto: ^3.0.5
  flutter_svg: ^2.0.17
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2
  window_manager: ^0.4.3
  desktop_drop: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
